apps:

  - name     : 'project-title'

    # context
    script   : server.js
    cwd: ./app/

    # variables
    args: ''
    node_args: []
    #interpreter_args: '-â€“harmony --harmony-modules --harmony_rest_parameters'
    env    :
        NODE_ENV: production

    # process config
    watch  : true
    ignore_watch : ['node_modules']
    exec_mode: fork
    #max_memory_restart: 150M
